# 异常捕获
|   语法    | 可选 | 解释       |  
|:-------:|:--:|:---------|  
|   try   |    | 可能会存在的异常 |  
| except  |    | 存在异常执行   |  
|  else   | ✓  | 没有异常执行   |  
| finally | ✓  | 有没有异常都执行 |
| Exception |   | 顶级异常 |
## 用法
### except用法
```python
try:  
    f = open("1.txt", "r", encoding="UTF-8")  # 可能存在的异常  
except FileNotFoundError as e:  
    print(f"出现了错误，代码：{e}")
```
#### 多个异常
```python
try:  
    f = open("1.txt", "r", encoding="UTF-8")  
    print(name)  
except (FileNotFoundError, NameError) as e:  
    print(f"出现了错误，代码：{e}")
```
### 全部用法
```python
try:  
    f = open("1.txt", "r", encoding="UTF-8")  # 可能存在的异常  
except Exception as e:  
    f = open("1.txt", "w", encoding="UTF-8")  # 如果文件不存在执行  
    print(e)  # 异常  
else:  
    print("没有异常")  # 没有异常执行  
finally:  
    f.close()  # 有没有异常都执行关闭文件
```
# 异常的传递
- 异常是具有传递性的
- 当所有函数都没有捕获异常的时候，程序就会报错
```python
def fun01():  
    print("这是fun01开始")  
    num = 1 / 0  
    print("这是fun01结束")  
  
  
def fun02():  
    print("这是fun02开始")  
    fun01()  
    print("这是fun02结束")  
  
  
def main():  
    try:  
        fun02()  
    except Exception as e:  
        print(f"异常{e}")  
  
  
main()
```
- 当函数func01中发生异常，并且没有捕获处理这个异常的时候，异常会传递到函数func02，当func02也没有捕获处理这个异常的时候main函数会捕获这个异常，这就是异常的传递性